DS: Build Tabs
firehydrant/design-system pull request #12
Opened 2021-05-11 16:55 UTC by nearbycoder

Adds the Tabs component as well as associated layout components within the Tabs component. Tabs, TabList, TabPanels, Tab, TabPanel .

2021-05-11 22:15 UTC, caseymhunt commented on lib/components/tabs/tabs.theme.js
> +      const selectedShadowOrientation =
> prop orientation should probably be used sparingly and the logic for switching that should live on a component by component basis in laddertruck.

I agree with you. I could see the breakpoint logic being baked into the component itself or in the application- I agree with you that we should start by expecting the implementation to handle switching the prop based on a media query. If for no other reason than if we give them a component that redraws itself arbitrarily it may confuse developers. (We could always add this functionality if it's asked for / becomes too repetitive in the codebase).

2021-05-11 22:35 UTC, caseymhunt requested changes
The small border-radius on the buttons is causing a a curved corner on both the inside and outside edges, contrary to the design (which calls for a straight indicator line with no curves). 
![example of curved edges on buttons](https://user-images.githubusercontent.com/2065615/117891599-cbcf9580-b27c-11eb-9ebc-70d405d4f4d4.png)

If style the `:after` pseudo element for these states, we should be able to achieve the straight line according to design intent. 

![styling the after pseudo element gives us a straight line](https://user-images.githubusercontent.com/2065615/117892982-38e42a80-b27f-11eb-84e8-906f708a7176.png)

2021-05-11 22:37 UTC, caseymhunt commented
> If we style the `:after` pseudo element for these states, we should be able to achieve the straight line according to design intent.

For the record, I quickly attempted to do this **without** success...
_tabs.theme.js:41_
```js
 _selected: {
    _after: {
      boxShadow: `${colors.purple[70]} ${selectedShadowOrientation}`,
   },
   ...
  ```

2021-05-11 22:50 UTC, nearbycoder commented
@caseymhunt hmmm there isn't any border radius in these elements. Wonder where that is coming from

2021-05-12 00:46 UTC, caseymhunt commented
> @caseymhunt hmmm there isn't any border radius in these elements. Wonder where that is coming from

👍🏼  Yeah you're right. I tracked it down. It's a user agent style (in this case on Microsoft Edge). I confirmed there is **no radius** on Safari. We may want to add a `borderRadius: 0` on these components for good measure to ensure the square edges.

2021-05-12 12:52 UTC, nearbycoder commented
@caseymhunt default borderRadius is set here https://github.com/firehydrant/design-system/pull/12/commits/c41ea1b160f3e26a67d23d96a330778443552714

2021-05-12 15:45 UTC, caseymhunt approved these changes

2021-05-12 15:46 UTC, merged