adding folder input icon from Lucide
firehydrant/design-system pull request #298
Opened 2022-08-31 01:05 UTC by katefarrar

<img width="357" alt="Screen Shot 2022-08-30 at 7 02 44 PM" src="https://user-images.githubusercontent.com/455281/187570249-584e11a4-5141-41c8-b9e4-a8f79a05c1c7.png">
<img width="345" alt="Screen Shot 2022-08-30 at 7 02 54 PM" src="https://user-images.githubusercontent.com/455281/187570254-4ba8f1e3-9f65-4ef4-9de3-91d5a9dafdaf.png">

Adding the `folderInput` icon from [Lucide](https://lucide.dev/icon/folder-input). Will be using this in the `Import` button in Import Services views.

2022-08-31 17:33 UTC, andreamorales approved these changes

2022-08-31 20:59 UTC, carissa-zukowski commented on lib/components/icons/FolderInput.jsx
> +    <path
@katefarrar from convo in slack (#team-design-system), if we want to move towards using the library, what is our motivation for pasting in the svg path here? if this icon is urgent we can coordinate with the FE team to prioritize. want to make sure that teams are aligned on how we want the DS to evolve and how FE is expected to interact.

2022-08-31 21:37 UTC, katefarrar commented on lib/components/icons/FolderInput.jsx
> +    <path
hi @carissa-zukowski! I worked with @andreamorales & @leskat47 on this. the thinking was that we didn't want the Import Services work to be blocked by not having this icon. Happy to set up a time to discuss more or figure out another solution if this isn't optimal. Thanks!

2022-09-01 17:34 UTC, theJakub requested changes
We are trying to move away from this pattern. Until we have Lucide in our project and DS reworked, please pick an icon from react-icons for your designs. react-icons is already in laddertruck and ready to use.

2022-09-08 21:01 UTC, katefarrar commented
Closing this without merging because we're going to use `RiFolderTransferLine` from [React Icons](https://react-icons.github.io/react-icons/). Thanks to everyone for the feedback and help!

2022-09-08 21:01 UTC, closed without merging