DS: Build Link
firehydrant/design-system pull request #7
Opened 2021-05-05 18:39 UTC by nearbycoder

Adds the link component to the design system with the proper design specs from https://www.figma.com/file/5Kra5sXVMkAjM62Gh8DpM8/Draft-Documentation?node-id=201%3A11

2021-05-05 18:41 UTC, nearbycoder reviewed
@caseymhunt good for initial overview

2021-05-05 18:41 UTC, nearbycoder commented on .storybook/preview.js
> +        value: '#182042',
Updated to match the dark design of our figma files.

2021-05-05 18:41 UTC, nearbycoder commented on lib/components/link/LinkText.js
> +export function LinkText({ variant, size, children, ...rest }) {
Very simple component that just wraps the text for providing the styles inside the anchor tag.

2021-05-05 18:41 UTC, nearbycoder commented on lib/components/link/link.theme.js
> +    display: 'inline-block',
Needed to update some of the defaults to prevent issues with default boxShadow and borders.

2021-05-05 18:42 UTC, nearbycoder commented
relevant storybook https://607731addb01d30021caeac2-xqjhcdnowf.chromatic.com/?path=/docs/link--default

2021-05-06 00:18 UTC, caseymhunt commented on lib/components/link/linktext.theme.js
> +      fontSize: `${font.fontSizes[5]}`,
😆 You know the drill. Theme-aware syntax weeeee

2021-05-06 00:19 UTC, caseymhunt requested changes
🥳  Minor nitpicks:
* adjust theme aware syntax
* ~~consider renaming stories per @jaxatto 's comment in Chromatic. ~~

2021-05-06 00:32 UTC, caseymhunt approved these changes

2021-05-06 16:58 UTC, merged