feat(alert): build alert component
firehydrant/design-system pull request #73
Opened 2021-07-12 19:56 UTC by hilaryBeck

[DS: Build Alert](https://app.clubhouse.io/firehydrant/story/18132/ds-build-alert)

Adds the alert component and stories.

2021-07-19 21:23 UTC, caseymhunt requested changes
Yaaaaa!!!! First component!!! 🥳  One question, one suggestion, summary is as follows:

- consider moving the `<Text/>` portion of the story into the component
- let's see if we can use an existing spacing unit in lieu of adding another per @jaxatto approval

2021-07-19 21:23 UTC, caseymhunt commented on lib/components/alert/Alert.stories.js
> +NeutralAlert.args = { variant: 'info', children: <Text color="grey.90" size="5">Neutral text</Text> };
We might want to consider moving the `<Text color="grey.90" size="5">...</Text>` into the component code itself since this is a design pattern across all the variants and prevents a component user from having to know to wrap their text in a component with these specific props. Thoughts?

2021-07-19 21:23 UTC, caseymhunt commented on lib/theme/space.theme.js
> +  mg1: '6px',
Did you have to introduce this based on design specs? If so, @jaxatto would you be ok with one of the existing space primitives or should we proceed with introducing another `mg` unit?

2021-07-19 22:19 UTC, hilaryBeck commented on lib/components/alert/Alert.stories.js
> +NeutralAlert.args = { variant: 'info', children: <Text color="grey.90" size="5">Neutral text</Text> };
i was debating that but i think i'll need to check in with jax as to what we want to pass — we want to be able to pass links as well, which might behave a little oddly if we're just passing a string? will double check and retool

2021-07-19 22:29 UTC, hilaryBeck commented on lib/theme/space.theme.js
> +  mg1: '6px',
yeah, if you look at `sg2` here: https://www.figma.com/file/5Kra5sXVMkAjM62Gh8DpM8/Draft-Documentation?node-id=534%3A1321 it's 6px. happy to remove if it's not necessary!

2021-07-20 18:42 UTC, jaxatto commented on lib/components/alert/Alert.stories.js
> +NeutralAlert.args = { variant: 'info', children: <Text color="grey.90" size="5">Neutral text</Text> };
Links in the body are a possibility, I do agree though that having defaulted style for the text is expected as a consumer imo

2021-07-20 18:45 UTC, jaxatto commented on lib/theme/space.theme.js
> +  mg1: '6px',
<img width="333" alt="Screen Shot 2021-07-20 at 1 43 00 PM" src="https://user-images.githubusercontent.com/6673768/126378265-35af78b4-2775-4464-8094-c2dccccb6d96.png">

This value is accurate, its purpose is to assist in vertical centering 

<img width="838" alt="Screen Shot 2021-07-20 at 1 44 09 PM" src="https://user-images.githubusercontent.com/6673768/126378371-19e0f9b9-a4f7-42fb-812b-d29f5a1b9c4c.png">

If these values weren't added, probably just haven't used them or run into them yet in other components.... though I'm certain they should have been used by now in something?

Also seeing the variable still says "mg0/1/etc", should be updated to "s". 

Thanks!

2021-07-20 18:49 UTC, caseymhunt commented on lib/components/alert/Alert.stories.js
> +NeutralAlert.args = { variant: 'info', children: <Text color="grey.90" size="5">Neutral text</Text> };
Since we're not abiding by strict typing in these props, in theory, a user could pass either a string and/or a node as a child. Maybe experiment with that and see if there are any potential trade-offs with that? My best guess at this point would be nested `span` coming from the Text + Link component.

2021-07-20 19:29 UTC, hilaryBeck commented on lib/theme/space.theme.js
> +  mg1: '6px',
cool to update the variable names separately, since a lot of components will be affected? happy to create a chore ticket for it

2021-07-20 19:52 UTC, caseymhunt commented on lib/components/alert/Alert.stories.js
> +NeutralAlert.args = { variant: 'info', children: <Text color="grey.90" size="5">Neutral text</Text> };
Looks like the markup tree is something like this...
```html
<p>
   <span>
      <a>
         <span>
...
```

It's a little verbose but I don't think it'll cause any issues with a11y parsing. I'm 👍🏼 to resolve this.

2021-07-20 20:13 UTC, caseymhunt approved these changes

2021-07-21 14:56 UTC, merged